import React from 'react'
import { storiesOf } from '@storybook/react'
import styled from '@emotion/styled'
import {
  IcoClosedIssue,
  IcoGithub,
  IcoOpenIssue,
  IcoStar,
} from '~/styles/icofont'

import sectionDecorator from './decorators/sectionDecorator'

const Line = styled.div`
  display: flex;
  align-items: center;
  margin-bottom: 10px;
  div {
    margin-left: 10px;
  }
`

storiesOf('Icons "i-"', module)
  .addDecorator(sectionDecorator)
  .add('all "i-" icons list', () => (
    <div>
      <h3>Icons showcase</h3>
      <p>These are autogenerated. For details see icofont section of README.md in the project root.</p>
      <p>Agree with your designer on a default grid for an icon glyph. Every icon should fit into that grid.
        They can have a padding within – if the designer decides so – but they should align horizontally with each other.
      </p>
      <p>
        SVGs for icons cannot use strokes, masks, styles. Icofont is monochromatic. If you wish to put
        a coloured svg in your project, use inline svg.
      </p>
      <Line>
        <IcoClosedIssue />
        <div>IcoClosedIssue</div>
      </Line>
      <Line>
        <IcoGithub />
        <div>IcoGithub</div>
      </Line>
      <Line>
        <IcoOpenIssue />
        <div>IcoOpenIssue</div>
      </Line>
      <Line>
        <IcoStar />
        <div>IcoStar</div>
      </Line>
    </div>
  ))
