import React from 'react'
import { storiesOf } from '@storybook/react'
import styled from '@emotion/styled'
import {
  IcoCog,
  IcoPersonalize,
  IcoSearch,
  IcoTag,
} from '~/styles/icofont'

import sectionDecorator from './decorators/sectionDecorator'

const Line = styled.div`
  display: flex;
  align-items: center;
  margin-bottom: 10px;
  div {
    margin-left: 10px;
  }
`

storiesOf('Icons "i-"', module)
  .addDecorator(sectionDecorator)
  .add('all "i-" icons list', () => (
    <div>
      <h3>Icons showcase</h3>
      <p>These are autogenerated. For details see icofont section of README.md in the project root.</p>
      <p>Agree with your designer on a default grid for an icon glyph. Every icon should fit into that grid.
        They can have a padding within if the designer wishes so, but they should align horizontally with each other.
      </p>
      <p>
        Svgs for icons cannot have strokes (shapes always), masks, styles. Icofont is monochromatic. If you wish to put
        a coloured svg in your project, use inline svg.
      </p>
      <p></p>
      <Line>
        <IcoCog />
        <div>IcoCog</div>
      </Line>
      <Line>
        <IcoPersonalize />
        <div>IcoPersonalize</div>
      </Line>
      <Line>
        <IcoSearch />
        <div>IcoSearch</div>
      </Line>
      <Line>
        <IcoTag />
        <div>IcoTag</div>
      </Line>
    </div>
  ))
